### ISSUE TITLE
Normalize temperatures?

### ISSUE THREAD

**Issue by gleachkr** [neferdata/allms#54]
Temperatures are currently represented by a u32. But OpenAI expects a number (decimal) between 0 and 2, and Anthropic expects a number between 0 and 1. Maybe it would make sense to normalize the temperatures per-LLM before sending off the API requests?

**Comment by darioalessandro** [comment]
Hey @gleachkr that is great point! 

How about using temp between [0-1] float and then scale to each of the LLM providers (Anthropic, OpenAI)?

Would that work?

**Comment by gleachkr** [comment]
Makes sense to me!

**Comment by darioalessandro** [comment]
@kamillitman what do you think?

**Comment by kamillitman** [comment]
Love the idea. Fits perfectly with what the crate is supposed to be doing. Let me work on a PR.

**Comment by kamillitman** [comment]
To avoid breaking changes to the constructor I kept the `temperature` input as `Option<u32>` that now represents a 0-100[%] of the range accepted by the model. 

For example:
- OpenAI: `Completions::new(OpenAIModels::Gpt4o, &key, None, Some(100u32))` will result in temperature of '2.0f32'. 
- Anthropic: `Completions::new(AnthropicModels::Claude3_5Sonnet, &key, None, Some(50u32))` will result in temperature of '0.5f32'.
